### ISSUE TITLE
Timer 

### ISSUE THREAD

**Issue by vetom** [lycan-city/werewolf-virtual-cards#64]
What do you guys think about adding a timer to the game view?

**Comment by nramirez** [comment]
👍 are we going to display this timer only for the Moderator or for all the participants? 

if we display it for everyone it will give a good sense of how long you need to keep your argument in order to convince others.

One thing is that the moderator might want to hard-stop the time for whatever reason he thinks, we need to consider adding a stop action (vote now) since we don't have votes now this action could be "reset timer".

**Comment by vetom** [comment]
The timer for the Moderator only, the main idea is a quick way to keep the track for days and nights.

**Comment by vetom** [comment]
Discarded feature.
